### ISSUE TITLE
Windows build is failing

### ISSUE THREAD

**Issue by soutaro** [ruby/rbs#1884]
The `mswin` on `windows-2019` builds are failing due to compilation error.

https://github.com/ruby/rbs/actions/runs/9443597826/job/26007613690

@MSP-Greg Can you help me to fix the problem? (Or I will skip the configuration.)

**Comment by MSP-Greg** [comment]
@soutaro

Not sure.  I know MSVC has always had compatibility issues with 'current' C standards.

It seems like the failures started with #1870 'Make c99, c23 compatible'.  But, the error message shown in CI is odd, it indicates that the issue is unrelated.

Also, the last passing mswin job used the same GHA runner image as the first failing job.  I've got 2022 & 2019 installed locally, so I'll see if I can repro.

**Comment by MSP-Greg** [comment]
@soutaro

I can repro the issue but I'm still trying to determine what change caused the failure.  The ucrt & mswin builds used in setup-ruby come from ruby-loco, and it (at present) only builds mswin with VS 2022.  I'm going to build mswin with VS 2019 locally and see what happens.  I'm AFK for a bit, not sure for how long...

**Comment by MSP-Greg** [comment]
I added a patch to the mswin build [win32-setup.mak.patch](https://github.com/MSP-Greg/ruby-loco/blob/843cb35d8383/mswin_patches/win32-setup.mak.patch), and it seems to fix the issue.

If it's okay here, I can open a PR in ruby/ruby.

It allows Ruby mswin builds using VS 2022 or later to also compile other items (ext gems, etc) using the previous version of VS.

**Comment by soutaro** [comment]
@MSP-Greg Thank you so much for your response and the patch!

I'm sorry, I don't know the detail of windows support in ruby/ruby. [Looks like](https://github.com/ruby/ruby/actions/workflows/windows.yml) they don't have build issues though...

**Comment by soutaro** [comment]
It compiles! 🎉  https://github.com/ruby/rbs/actions/runs/9479776888/job/26157488917
I really appreciate your help!

**Comment by soutaro** [comment]
> Everyone else is just using 'windows-latest'.

Hmm. Do you think testing only `windows-latest` makes more sense? I have no strong opinion on this in fact.
(Note that the build matrix is [what you write for the project](https://github.com/ruby/rbs/commit/378989508a1849e082d7ac9e879cb9027be0cba6). 😆)

**Comment by MSP-Greg** [comment]
> Do you think testing only windows-latest makes more sense?

If you use `windows-latest`, you don't have to keep an eye on GHA setup.  Or, you'll be updated to the latest image when it's available.  Conversely, some repos would prefer to not have an 'automatic change', which could break CI.

Yes, I did set up the GHA workflow at the time.  The `windows-2022` GHA image was first available (as a release) with the 10-Jan-2022 image, it was in beta a few months before that.

> I have no strong opinion on this in fact.

I feel the same.  Given that the actual VS build tools are free, and a paid version is now a `subscription`, I don't see why people would still be using VS 2019.  But, GHA is still supporting it with their runner image...

**Comment by soutaro** [comment]
Thanks Greg,
I will revise the CI setup to use only `windows-latest`. (And add some released ruby versions.)
